/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufjf.dcc025.interfacegrafica;

import javax.swing.JButton;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author guilherme
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        JButton [] btns = {botaoPrecisoAssistir, botaoAssistindo};
        
        for(JButton btn : btns) {
            btn.setBackground(new Color(248, 161, 31));
            btn.setUI(new BasicButtonUI());
            
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent me) {
                }

                @Override
                public void mousePressed(MouseEvent me) {
                }

                @Override
                public void mouseReleased(MouseEvent me) {
                }

                @Override
                public void mouseEntered(MouseEvent me) {
                    btn.setBackground(new Color(255,200,118));
                }

                @Override
                public void mouseExited(MouseEvent me) {
                    btn.setBackground(new Color(248, 161, 31));
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        raiz = new javax.swing.JPanel();
        fundoBase = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        subtitulo = new javax.swing.JLabel();
        botaoPrecisoAssistir = new javax.swing.JButton();
        botaoAssistindo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        raiz.setLayout(new java.awt.BorderLayout());

        fundoBase.setBackground(new java.awt.Color(30, 29, 29));
        fundoBase.setPreferredSize(new java.awt.Dimension(940, 550));

        titulo.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 92)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("TÔ ON");
        titulo.setToolTipText("");
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titulo.setMaximumSize(new java.awt.Dimension(153, 49));

        subtitulo.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        subtitulo.setForeground(new java.awt.Color(255, 255, 255));
        subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo.setText("FILMES E SÉRIES");

        botaoPrecisoAssistir.setBackground(new java.awt.Color(255, 153, 0));
        botaoPrecisoAssistir.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        botaoPrecisoAssistir.setForeground(new java.awt.Color(255, 255, 255));
        botaoPrecisoAssistir.setText("Preciso Assistir");
        botaoPrecisoAssistir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoPrecisoAssistir.setName(""); // NOI18N
        botaoPrecisoAssistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPrecisoAssistirActionPerformed(evt);
            }
        });

        botaoAssistindo.setBackground(new java.awt.Color(255, 153, 0));
        botaoAssistindo.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        botaoAssistindo.setForeground(new java.awt.Color(255, 255, 255));
        botaoAssistindo.setText("Assistindo");
        botaoAssistindo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoAssistindo.setName(""); // NOI18N

        javax.swing.GroupLayout fundoBaseLayout = new javax.swing.GroupLayout(fundoBase);
        fundoBase.setLayout(fundoBaseLayout);
        fundoBaseLayout.setHorizontalGroup(
            fundoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoBaseLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(fundoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fundoBaseLayout.createSequentialGroup()
                        .addComponent(botaoPrecisoAssistir, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(botaoAssistindo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        fundoBaseLayout.setVerticalGroup(
            fundoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoBaseLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitulo)
                .addGap(105, 105, 105)
                .addGroup(fundoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(botaoAssistindo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPrecisoAssistir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        raiz.add(fundoBase, java.awt.BorderLayout.CENTER);

        getContentPane().add(raiz, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPrecisoAssistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPrecisoAssistirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPrecisoAssistirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAssistindo;
    private javax.swing.JButton botaoPrecisoAssistir;
    private javax.swing.JPanel fundoBase;
    private javax.swing.JPanel raiz;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
